// src/lib/meta/defaultTables.ts
import { AppTable, AppColumn } from "./types";

export const DEFAULT_TABLES: AppTable[] = [
  {
    id: "plant-intake",
    name: "Plant Intake",
    slug: "plant-intake",
    createdBy: "system",
    createdAt: new Date(),
    isDeleted: false,
  },
  {
    id: "product-intake",
    name: "Product Intake",
    slug: "product-intake",
    createdBy: "system",
    createdAt: new Date(),
    isDeleted: false,
  },
  {
    id: "transplant-log",
    name: "Transplant Log",
    slug: "transplant-log",
    createdBy: "system",
    createdAt: new Date(),
    isDeleted: false,
  },
  {
    id: "treatment-tracking",
    name: "Treatment Tracking",
    slug: "treatment-tracking",
    createdBy: "system",
    createdAt: new Date(),
    isDeleted: false,
  },
  {
    id: "fertilizer-log",
    name: "Fertilizer Log",
    slug: "fertilizer-log",
    createdBy: "system",
    createdAt: new Date(),
    isDeleted: false,
  },
  {
    id: "overhead-expenses",
    name: "Overhead Expenses",
    slug: "overhead-expenses",
    createdBy: "system",
    createdAt: new Date(),
    isDeleted: false,
  },
  {
    id: "sales",
    name: "Sales",
    slug: "sales",
    createdBy: "system",
    createdAt: new Date(),
    isDeleted: false,
  },
  {
    id: "pricing",
    name: "Pricing",
    slug: "pricing",
    createdBy: "system",
    createdAt: new Date(),
    isDeleted: false,
  },
];

export const DEFAULT_COLUMNS: AppColumn[] = [
  // ========================================
  // PLANT INTAKE (8 columns)
  // ========================================
  {
    id: "dateReceived",
    tableId: "plant-intake",
    name: "Date Received",
    type: "date",
    isComputed: false,
    orderIndex: 0,
    isVisible: true,
    required: true,
  },
  {
    id: "sku",
    tableId: "plant-intake",
    name: "SKU",
    type: "text",
    isComputed: false,
    orderIndex: 1,
    isVisible: true,
  },
  {
    id: "genus",
    tableId: "plant-intake",
    name: "Genus",
    type: "text",
    isComputed: false,
    orderIndex: 2,
    isVisible: true,
  },
  {
    id: "cultivar",
    tableId: "plant-intake",
    name: "Cultivar",
    type: "text",
    isComputed: false,
    orderIndex: 3,
    isVisible: true,
  },
  {
    id: "size",
    tableId: "plant-intake",
    name: "Size",
    type: "text",
    isComputed: false,
    orderIndex: 4,
    isVisible: true,
  },
  {
    id: "quantity",
    tableId: "plant-intake",
    name: "Quantity",
    type: "number",
    isComputed: false,
    orderIndex: 5,
    isVisible: true,
  },
  {
    id: "vendor",
    tableId: "plant-intake",
    name: "Vendor",
    type: "text",
    isComputed: false,
    orderIndex: 6,
    isVisible: true,
  },
  {
    id: "notes",
    tableId: "plant-intake",
    name: "Notes",
    type: "text",
    isComputed: false,
    orderIndex: 7,
    isVisible: true,
  },

  // ========================================
  // PRODUCT INTAKE (11 columns)
  // ========================================
  {
    id: "dateReceived",
    tableId: "product-intake",
    name: "Date Received",
    type: "date",
    isComputed: false,
    orderIndex: 0,
    isVisible: true,
    required: true,
  },
  {
    id: "productName",
    tableId: "product-intake",
    name: "Product Name",
    type: "text",
    isComputed: false,
    orderIndex: 1,
    isVisible: true,
  },
  {
    id: "category",
    tableId: "product-intake",
    name: "Category",
    type: "text",
    isComputed: false,
    orderIndex: 2,
    isVisible: true,
    placeholder: "e.g., Pots, Soil, Tools, Fertilizer",
  },
  {
    id: "brand",
    tableId: "product-intake",
    name: "Brand",
    type: "text",
    isComputed: false,
    orderIndex: 3,
    isVisible: true,
  },
  {
    id: "sku",
    tableId: "product-intake",
    name: "SKU",
    type: "text",
    isComputed: false,
    orderIndex: 4,
    isVisible: true,
  },
  {
    id: "quantity",
    tableId: "product-intake",
    name: "Quantity",
    type: "number",
    isComputed: false,
    orderIndex: 5,
    isVisible: true,
  },
  {
    id: "unit",
    tableId: "product-intake",
    name: "Unit",
    type: "text",
    isComputed: false,
    orderIndex: 6,
    isVisible: true,
    placeholder: "e.g., bags, boxes, each",
  },
  {
    id: "unitCost",
    tableId: "product-intake",
    name: "Unit Cost",
    type: "currency",
    isComputed: false,
    orderIndex: 7,
    isVisible: true,
  },
  {
    id: "totalCost",
    tableId: "product-intake",
    name: "Total Cost",
    type: "currency",
    isComputed: false,
    orderIndex: 8,
    isVisible: true,
  },
  {
    id: "vendor",
    tableId: "product-intake",
    name: "Vendor",
    type: "text",
    isComputed: false,
    orderIndex: 9,
    isVisible: true,
  },
  {
    id: "notes",
    tableId: "product-intake",
    name: "Notes",
    type: "text",
    isComputed: false,
    orderIndex: 10,
    isVisible: true,
  },

  // ========================================
  // TRANSPLANT LOG (11 columns)
  // ========================================
  {
    id: "transplantDate",
    tableId: "transplant-log",
    name: "Transplant Date",
    type: "date",
    isComputed: false,
    orderIndex: 0,
    isVisible: true,
    required: true,
  },
  {
    id: "plantName",
    tableId: "transplant-log",
    name: "Plant Name",
    type: "text",
    isComputed: false,
    orderIndex: 1,
    isVisible: true,
  },
  {
    id: "genus",
    tableId: "transplant-log",
    name: "Genus",
    type: "text",
    isComputed: false,
    orderIndex: 2,
    isVisible: true,
  },
  {
    id: "cultivar",
    tableId: "transplant-log",
    name: "Cultivar",
    type: "text",
    isComputed: false,
    orderIndex: 3,
    isVisible: true,
  },
  {
    id: "fromSize",
    tableId: "transplant-log",
    name: "From Size",
    type: "text",
    isComputed: false,
    orderIndex: 4,
    isVisible: true,
    placeholder: "e.g., 2 inch, 4 inch",
  },
  {
    id: "toSize",
    tableId: "transplant-log",
    name: "To Size",
    type: "text",
    isComputed: false,
    orderIndex: 5,
    isVisible: true,
    placeholder: "e.g., 1 gallon, 2 gallon",
  },
  {
    id: "quantity",
    tableId: "transplant-log",
    name: "Quantity",
    type: "number",
    isComputed: false,
    orderIndex: 6,
    isVisible: true,
  },
  {
    id: "soilMix",
    tableId: "transplant-log",
    name: "Soil Mix",
    type: "text",
    isComputed: false,
    orderIndex: 7,
    isVisible: true,
  },
  {
    id: "location",
    tableId: "transplant-log",
    name: "Location",
    type: "text",
    isComputed: false,
    orderIndex: 8,
    isVisible: true,
    placeholder: "e.g., Greenhouse A, Bench 3",
  },
  {
    id: "employee",
    tableId: "transplant-log",
    name: "Employee",
    type: "text",
    isComputed: false,
    orderIndex: 9,
    isVisible: true,
  },
  {
    id: "notes",
    tableId: "transplant-log",
    name: "Notes",
    type: "text",
    isComputed: false,
    orderIndex: 10,
    isVisible: true,
  },

  // ========================================
  // TREATMENT TRACKING (12 columns)
  // ========================================
  {
    id: "treatmentDate",
    tableId: "treatment-tracking",
    name: "Treatment Date",
    type: "date",
    isComputed: false,
    orderIndex: 0,
    isVisible: true,
    required: true,
  },
  {
    id: "plantName",
    tableId: "treatment-tracking",
    name: "Plant Name",
    type: "text",
    isComputed: false,
    orderIndex: 1,
    isVisible: true,
  },
  {
    id: "genus",
    tableId: "treatment-tracking",
    name: "Genus",
    type: "text",
    isComputed: false,
    orderIndex: 2,
    isVisible: true,
  },
  {
    id: "cultivar",
    tableId: "treatment-tracking",
    name: "Cultivar",
    type: "text",
    isComputed: false,
    orderIndex: 3,
    isVisible: true,
  },
  {
    id: "treatmentType",
    tableId: "treatment-tracking",
    name: "Treatment Type",
    type: "text",
    isComputed: false,
    orderIndex: 4,
    isVisible: true,
    placeholder: "e.g., Pesticide, Fungicide, Herbicide",
  },
  {
    id: "product",
    tableId: "treatment-tracking",
    name: "Product",
    type: "text",
    isComputed: false,
    orderIndex: 5,
    isVisible: true,
  },
  {
    id: "dosage",
    tableId: "treatment-tracking",
    name: "Dosage",
    type: "text",
    isComputed: false,
    orderIndex: 6,
    isVisible: true,
    placeholder: "e.g., 2 oz per gallon",
  },
  {
    id: "quantity",
    tableId: "treatment-tracking",
    name: "Quantity Treated",
    type: "number",
    isComputed: false,
    orderIndex: 7,
    isVisible: true,
  },
  {
    id: "location",
    tableId: "treatment-tracking",
    name: "Location",
    type: "text",
    isComputed: false,
    orderIndex: 8,
    isVisible: true,
  },
  {
    id: "reason",
    tableId: "treatment-tracking",
    name: "Reason",
    type: "text",
    isComputed: false,
    orderIndex: 9,
    isVisible: true,
    placeholder: "e.g., Aphid infestation, Powdery mildew",
  },
  {
    id: "employee",
    tableId: "treatment-tracking",
    name: "Employee",
    type: "text",
    isComputed: false,
    orderIndex: 10,
    isVisible: true,
  },
  {
    id: "notes",
    tableId: "treatment-tracking",
    name: "Notes",
    type: "text",
    isComputed: false,
    orderIndex: 11,
    isVisible: true,
  },

  // ========================================
  // FERTILIZER LOG (12 columns)
  // ========================================
  {
    id: "applicationDate",
    tableId: "fertilizer-log",
    name: "Application Date",
    type: "date",
    isComputed: false,
    orderIndex: 0,
    isVisible: true,
    required: true,
  },
  {
    id: "plantName",
    tableId: "fertilizer-log",
    name: "Plant Name",
    type: "text",
    isComputed: false,
    orderIndex: 1,
    isVisible: true,
  },
  {
    id: "genus",
    tableId: "fertilizer-log",
    name: "Genus",
    type: "text",
    isComputed: false,
    orderIndex: 2,
    isVisible: true,
  },
  {
    id: "cultivar",
    tableId: "fertilizer-log",
    name: "Cultivar",
    type: "text",
    isComputed: false,
    orderIndex: 3,
    isVisible: true,
  },
  {
    id: "fertilizerType",
    tableId: "fertilizer-log",
    name: "Fertilizer Type",
    type: "text",
    isComputed: false,
    orderIndex: 4,
    isVisible: true,
    placeholder: "e.g., Liquid, Granular, Slow-release",
  },
  {
    id: "brand",
    tableId: "fertilizer-log",
    name: "Brand",
    type: "text",
    isComputed: false,
    orderIndex: 5,
    isVisible: true,
  },
  {
    id: "npkRatio",
    tableId: "fertilizer-log",
    name: "NPK Ratio",
    type: "text",
    isComputed: false,
    orderIndex: 6,
    isVisible: true,
    placeholder: "e.g., 20-20-20, 10-10-10",
  },
  {
    id: "applicationRate",
    tableId: "fertilizer-log",
    name: "Application Rate",
    type: "text",
    isComputed: false,
    orderIndex: 7,
    isVisible: true,
    placeholder: "e.g., 1 tbsp per gallon, 100 ppm",
  },
  {
    id: "quantity",
    tableId: "fertilizer-log",
    name: "Quantity",
    type: "number",
    isComputed: false,
    orderIndex: 8,
    isVisible: true,
  },
  {
    id: "location",
    tableId: "fertilizer-log",
    name: "Location",
    type: "text",
    isComputed: false,
    orderIndex: 9,
    isVisible: true,
    placeholder: "e.g., Greenhouse A, Bench 3",
  },
  {
    id: "employee",
    tableId: "fertilizer-log",
    name: "Employee",
    type: "text",
    isComputed: false,
    orderIndex: 10,
    isVisible: true,
  },
  {
    id: "notes",
    tableId: "fertilizer-log",
    name: "Notes",
    type: "text",
    isComputed: false,
    orderIndex: 11,
    isVisible: true,
  },

  // ========================================
  // OVERHEAD EXPENSES (9 columns)
  // ========================================
  {
    id: "expenseDate",
    tableId: "overhead-expenses",
    name: "Expense Date",
    type: "date",
    isComputed: false,
    orderIndex: 0,
    isVisible: true,
    required: true,
  },
  {
    id: "category",
    tableId: "overhead-expenses",
    name: "Category",
    type: "text",
    isComputed: false,
    orderIndex: 1,
    isVisible: true,
    placeholder: "e.g., Utilities, Rent, Insurance, Labor",
  },
  {
    id: "description",
    tableId: "overhead-expenses",
    name: "Description",
    type: "text",
    isComputed: false,
    orderIndex: 2,
    isVisible: true,
  },
  {
    id: "vendor",
    tableId: "overhead-expenses",
    name: "Vendor",
    type: "text",
    isComputed: false,
    orderIndex: 3,
    isVisible: true,
  },
  {
    id: "amount",
    tableId: "overhead-expenses",
    name: "Amount",
    type: "currency",
    isComputed: false,
    orderIndex: 4,
    isVisible: true,
    required: true,
  },
  {
    id: "paymentMethod",
    tableId: "overhead-expenses",
    name: "Payment Method",
    type: "text",
    isComputed: false,
    orderIndex: 5,
    isVisible: true,
    placeholder: "e.g., Cash, Check, Credit Card, ACH",
  },
  {
    id: "invoiceNumber",
    tableId: "overhead-expenses",
    name: "Invoice Number",
    type: "text",
    isComputed: false,
    orderIndex: 6,
    isVisible: true,
  },
  {
    id: "employee",
    tableId: "overhead-expenses",
    name: "Employee",
    type: "text",
    isComputed: false,
    orderIndex: 7,
    isVisible: true,
    placeholder: "Who recorded this expense",
  },
  {
    id: "notes",
    tableId: "overhead-expenses",
    name: "Notes",
    type: "text",
    isComputed: false,
    orderIndex: 8,
    isVisible: true,
  },

  // ========================================
  // SALES (12 columns)
  // ========================================
  {
    id: "saleDate",
    tableId: "sales",
    name: "Sale Date",
    type: "date",
    isComputed: false,
    orderIndex: 0,
    isVisible: true,
    required: true,
  },
  {
    id: "customerName",
    tableId: "sales",
    name: "Customer Name",
    type: "text",
    isComputed: false,
    orderIndex: 1,
    isVisible: true,
  },
  {
    id: "plantName",
    tableId: "sales",
    name: "Plant Name",
    type: "text",
    isComputed: false,
    orderIndex: 2,
    isVisible: true,
  },
  {
    id: "genus",
    tableId: "sales",
    name: "Genus",
    type: "text",
    isComputed: false,
    orderIndex: 3,
    isVisible: true,
  },
  {
    id: "cultivar",
    tableId: "sales",
    name: "Cultivar",
    type: "text",
    isComputed: false,
    orderIndex: 4,
    isVisible: true,
  },
  {
    id: "size",
    tableId: "sales",
    name: "Size",
    type: "text",
    isComputed: false,
    orderIndex: 5,
    isVisible: true,
    placeholder: "e.g., 4 inch, 1 gallon",
  },
  {
    id: "quantity",
    tableId: "sales",
    name: "Quantity",
    type: "number",
    isComputed: false,
    orderIndex: 6,
    isVisible: true,
  },
  {
    id: "unitPrice",
    tableId: "sales",
    name: "Unit Price",
    type: "currency",
    isComputed: false,
    orderIndex: 7,
    isVisible: true,
  },
  {
    id: "totalPrice",
    tableId: "sales",
    name: "Total Price",
    type: "currency",
    isComputed: false,
    orderIndex: 8,
    isVisible: true,
  },
  {
    id: "paymentMethod",
    tableId: "sales",
    name: "Payment Method",
    type: "text",
    isComputed: false,
    orderIndex: 9,
    isVisible: true,
    placeholder: "e.g., Cash, Credit Card, Check",
  },
  {
    id: "employee",
    tableId: "sales",
    name: "Employee",
    type: "text",
    isComputed: false,
    orderIndex: 10,
    isVisible: true,
  },
  {
    id: "notes",
    tableId: "sales",
    name: "Notes",
    type: "text",
    isComputed: false,
    orderIndex: 11,
    isVisible: true,
  },

  // ========================================
  // PRICING (9 columns)
  // ========================================
  {
    id: "plantName",
    tableId: "pricing",
    name: "Plant Name",
    type: "text",
    isComputed: false,
    orderIndex: 0,
    isVisible: true,
    required: true,
  },
  {
    id: "genus",
    tableId: "pricing",
    name: "Genus",
    type: "text",
    isComputed: false,
    orderIndex: 1,
    isVisible: true,
  },
  {
    id: "cultivar",
    tableId: "pricing",
    name: "Cultivar",
    type: "text",
    isComputed: false,
    orderIndex: 2,
    isVisible: true,
  },
  {
    id: "size",
    tableId: "pricing",
    name: "Size",
    type: "text",
    isComputed: false,
    orderIndex: 3,
    isVisible: true,
    placeholder: "e.g., 4 inch, 1 gallon",
  },
  {
    id: "basePrice",
    tableId: "pricing",
    name: "Base Price",
    type: "currency",
    isComputed: false,
    orderIndex: 4,
    isVisible: true,
  },
  {
    id: "markup",
    tableId: "pricing",
    name: "Markup",
    type: "percent",
    isComputed: false,
    orderIndex: 5,
    isVisible: true,
    placeholder: "e.g., 25 for 25%",
  },
  {
    id: "finalPrice",
    tableId: "pricing",
    name: "Final Price",
    type: "currency",
    isComputed: false,
    orderIndex: 6,
    isVisible: true,
    required: true,
  },
  {
    id: "category",
    tableId: "pricing",
    name: "Category",
    type: "text",
    isComputed: false,
    orderIndex: 7,
    isVisible: true,
    placeholder: "e.g., Perennials, Annuals, Shrubs",
  },
  {
    id: "notes",
    tableId: "pricing",
    name: "Notes",
    type: "text",
    isComputed: false,
    orderIndex: 8,
    isVisible: true,
  },
];